defaults:
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: train_model
    storage: null
    n_trials: 10
    n_jobs: 1
    params:
      max_depth: range(5,100)
      min_samples_split: range(2, 1000)

max_depth: 1000000
min_samples_split: 2
random_state: 23